
services:
  broker:
    image: eclipse-mosquitto:2
    container_name: broker
    ports: ["1883:1883"]
    volumes:
      - ./broker/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    restart: unless-stopped

  edge:
    build: ./edge
    container_name: edge
    environment:
      - BROKER_HOST=broker
      - BROKER_PORT=1883
      - MODEL_NAME=mv3_small   # mv3_small|mv3_large|mv2|eff0|eff2
      - TORCH_THREADS=4
    depends_on:
      - broker
    restart: unless-stopped
